version: '3.1'

services:
  app:
    image: veselinpetkov/sportsnews:amd64
    container_name: sportsnews
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - sportsnews_db

  db:
    image: mysql
    container_name: sportsnews_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d/:ro


